---
title: Research
toc: true
toc-location: right
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
---

<div style="text-align: center;">
  <a href="https://scholar.google.com/citations?user=be3YYWMAAAAJ&hl=en&oi=ao" target="_blank" title="Google Scholar" style="margin: 0 40px;"><i class="ai ai-google-scholar ai-2x"></i></a>
  <a href="https://orcid.org/0000-0002-8163-7956" target="_blank" title="ORCID" style="margin: 0 40px;"><i class="ai ai-orcid ai-2x"></i></a>
  <a href="https://www.researchgate.net/profile/Colin-Kuehl" target="_blank" title="ResearchGate" style="margin: 0 40px;"><i class="ai ai-researchgate ai-2x"></i></a>
</div>

## Overview 

My research focuses on the politics of environmental behavior across multiple scales and across various issue areas. It applies political science frameworks to understanding the social a causes of environmental problems, focusing on what motivates actors to contribute to environmental protection. It begins with an assumption that we have sufficient scientific knowledge and viable solutions to most environmental challenges, political barriers remain the primary obstacle to progress. I examine these barriers across multiple levels of analysis using rigorous methods, including experiments, text-as-data techniques, and traditional large-N analysis. I also frequently collaborate with scholars in fields such as social psychology, communication, ecology, and geology to address problems more comprehensively. This interdisciplinary approach allows me to bridge academic divides and contribute insights that inform both political scientists and the broader environmental community.


----

## Recent Publications
- 2026 “Clinging to Power: Status Threat and Attitudes toward Renewable Energy” Tammie-Louise Finnegan, Cassandra Epping, Nick Florian, and **Colin Kuehl**. [Environmental Politics](https://doi.org/10.1080/09644016.2025.2604372)

- 2025 “Centering people in restoration messaging increases their likelihood to engage in restoration actions” **Colin Kuehl**, Todd Buck, Christiana Guthrie, Oliver Meyers, Emman Mohammad, Quinn Sedig, Shupei Yuan and Holly P. Jones. 33: e70155. [Restoration Ecology](https://doi.org/10.1111/rec.70155)

- 2025 “Tweeting to Conserve: An Analysis of Water District Messaging during the California Drought” **Colin Kuehl** in Nic Guehlstorf (ed.) [Environmental Policy Science’s Exploration for Innovative Data](https://link.springer.com/book/10.1007/978-3-031-90889-7) Springer

- 2025 “Varied Accounts of Quality and Rigor in Qualitative Research in Political Science” Alesha Porisky, Aarie Glas, and **Colin Kuehl** in Uwe Flick (ed.) [SAGE Handbook of Qualitative Research Quality](https://us.sagepub.com/en-us/nam/the-sage-handbook-of-qualitative-research-quality/book283878#description) 


See CV or the links above for a full list of publications.


## Ongoing Research Projects





----

### Public Preferences for Global Cooperation

My book attempts to understand public attitudes around to world toward global environmental cooperation, like the Paris Agreement. While canonical models suggest issues like climate change are the ultimate collective action problem, the public doesn't seem to think so. A trove of observational and experimental studies show that individuals are overwhelming supportive of cooperative efforts and don't think about these issues in terms of guarantees of reciprocity. The book takes a deep dive into these issues and tries to understand how individuals around the world can drive more effective global environmental governance. 

### Understanding Sustainability Communications using Textual Data

Textual data is underutilized in the study of environmental politics. In a series of projects I'm working on with varios co-authors this work uses multiple text-as-data techniques to understand how actors, like local governments and private governance actors,actually communicate about sustainability issues. 

### Accountability and Action in Southeast Asian Environmental Politics

Our planet’s path to environmental sustainabilty surely runs through Southeast Asia. No other region in the world better exemplifies the challenges and opportunities 


*If you are interested in getting involved in these projects or hearing more please do not hesitate to reach out to me*
