# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Colin Kuehl"                                # Your name
  description: "Assistant Professor of Political Science and Environmental Studies"   # A brief slogan (optional)
  image: img/bridge1.png
  
  favicon: img/bridge2.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/niu.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Research"
        href: Research/researchindex.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      - icon: twitter
        href: https://twitter.com/cpkuehl
      - icon: envelope
        aria-label: email
        href: "mailto:ckuehl@niu.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true